---
generator: jekyll
version: ''
upload_path: "/images/"
frontmatter_file_url_template: "/images/"
body_file_url_template: "/uploads/:year:/:month:/:day:"
new_page_extension: md
auto_deploy: false
admin_path:
webhook_url:
collections:
  jobs:
    default_front_matter_template: posts 
